apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaegersampletraces.fullname" . }}
  labels:
    {{- include "jaegersampletraces.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: UDP
      name: http
  selector:
    {{- include "jaegersampletraces.selectorLabels" . | nindent 4 }}
